#!/bin/sh

# 入力コマンドを取得
command=$(ps -ocommand= -p $PPID)
pattern="\-\-force|\-f"

if [[ $command =~ $pattern ]] ; then
  # コマンドラインに確認文を出力
  read -rp 'Do you really force push? (yes/no):' input < /dev/tty
  yes_pattern="^yes$|^y$|^Y$|^YES$|^Yes$"

  if [[ $input =~ $yes_pattern ]]; then
    echo "do force push"
  else
    # yes 以外であればエラーを返す
    exit 1;
  fi
fi