#!/bin/sh
branch=`git symbolic-ref HEAD --short`
pattern="master|main|develop|development"

# mainブランチとかmasterブランチに直接コミットしないようにする
if [[ $branch =~ $pattern ]]; then
  echo "Cannot commit to $branch branch directly."
  exit 1
fi