#!/bin/sh

# 入力コマンドを取得
command=$(ps -ocommand= -p $PPID)

if [[ $command =~ '\-\-force|\-f' ]] ; then

  # コマンドラインに確認文を出力
  read -rp 'force pushを実行しますか？ (yes/no):' input < /dev/tty
  if [ "${input}" = "yes" ]; then
    echo "do force push"
  else
    # yes 以外であればエラーを返す
    exit 1;
  fi
fi